name := site.cabsec

tasks := genSVG_ genSite_
tasks := $(foreach t,$(tasks),flow/$t)

.DEFAULT_GOAL := help
.PHONY: import flow export lint format $(tasks)

help:
	$(info Please use 'make <target>', where <target> is one of)
	$(info )
	$(info   install     install packages and prepare software environment)
	$(info )
	$(info   import      import data required for processing document flow)
	$(info   flow        execute the tasks in the document flow)
	$(info   export      export the data generated by the document flow)
	$(info )
	$(info   lint        run the code linters)
	$(info   format      reformat code)
	$(info )
	$(info Check the makefile to know exactly what each target is doing.)
	@echo # dummy command


install: pyproject.toml
	poetry install --only=dev
	npm ci
	mkdir genSVG_/output;
	mkdir genSite_/output;

import: 
	poetry run op importall import/

flow: $(tasks)
$(tasks):
	poetry run make -C $@

lint:
	poetry run black -q .
	poetry run ruff .

format:
	poetry run black -q .
	poetry run ruff --fix .


export: format lint
	poetry run op exportsite flow/genSite_ docs/

