
.PHONY: help clean lint format test pre-commit test

name := site.cabsec
instal_stamp := .install.stamp
poetry := $(shell command -v poetry 2> /dev/null)
npm := $(shell command -v npm > /dev/null)
sources := flow/genSite_/src 

.DEFAULT_GOAL := help


help:
	@echo "Please use 'make <target>' where <target> is one of"
	@echo ""
	@echo "  install     install packages and prepare software environment"
	@echo ""
	@echo "  import      import data required for processing data flow"
	@echo "  flow        execute the tasks in the data flow"
	@echo "  export      export the data generated by the data flow"
	@echo ""
	@echo "  clean       remove all temporary files"
	@echo "  lint        run the code linters"
	@echo "  format      reformat code"
	@echo "  test        run all the tests"
	@echo ""
	@echo "Check the Makefile to know exactly what each target is doing."

install: $(install_stamp)
$(install_stamp): pyproject.toml poetry.lock
	@if [ -z $(poetry) ]; then echo "Poetry could not be found. See https://python-poetry.org/docs/"; exit 2; fi
	@if [ -z $(npm) ]; then echo "Node could not be found. See https://nodejs.org/en/"; exit 2; fi

	$(poetry) install
	$(npm) ci
	touch $(install_stamp)

clean:
	find . -type d -name "__pycache__" | xargs rm -rf {};
	rm -rf $(install_stamp) .coverage .mypy_cache


lint: $(install_stamp)
	$(poetry) run isort --profile=black --lines-after-imports=2 --check-only ./tests/ $(NAME)
	$(poetry) run black --check ./tests/ $(NAME) --diff
	$(poetry) run flake8 --ignore=W503,E501 ./tests/ $(NAME)
	$(poetry) run mypy ./tests/ $(NAME) --ignore-missing-imports
	$(poetry) run bandit -r $(NAME) -s B608


format: $(install_stamp)
	$(poetry) run isort --profile=black --lines-after-imports=2 ./tests/ $(NAME)
	$(poetry) run black ./tests/ $(NAME)


test: $(install_stamp)
	$(poetry) run pytest ./tests/ --cov-report term-missing --cov-fail-under 100 --cov $(NAME)
